[package]
name = "nethernet"
version = "0.0.1"
edition = "2024"
rust-version = "1.85"

[dependencies]
thiserror = { workspace = true }
tokio = { workspace = true }
rand = { workspace = true }
bytes = { workspace = true }
webrtc = { workspace = true }