[package]
name = "bedrock"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.49.0", features = ["full"] }
tokio-raknet = "0.2.0"
tracing = "0.1.44"
tracing-subscriber = "0.3.22"
